project:
  type: website
  output-dir: docs

website:
  search: true
  title: "quarto-test-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: test.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



